name = "rolldoradoapp-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradoapp.com.gr"
HMAC_KEY = "160da8230932354dfafdfb73511e239fc781348e48ddc296cc2a7e71545a0d71"
COOKIE_NAME = "k0e"
PLAY_PATH = "try-now"
BUTTON_ID = "p5ba0096c9d00fd2ceb5995a8895c07ad"
GATE_SALT = "d19b07656bd92002"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "rqcy"
CTA_SELECTOR = ".play-button"
